name: Make Signing Key

on:
  workflow_dispatch:

jobs:
  makekey:
    runs-on: ubuntu-latest
    steps:
    - name: Generate keystore
      run: |
        keytool -genkeypair -v \
          -keystore release.keystore \
          -alias phonesim1 \
          -keyalg RSA -keysize 2048 \
          -validity 10950 \
          -storepass 'PhoneSim1!2024' \
          -keypass 'PhoneSim1!2024' \
          -dname "CN=Phone Simulator 1, OU=Games, O=Sina, L=Tehran, C=IR"
    - name: Create base64 text
      run: base64 -w0 release.keystore > keystore-base64.txt
    - name: Upload key files
      uses: actions/upload-artifact@v4
      with:
        name: signing-key
        path: |
          release.keystore
          keystore-base64.txt
        retention-days: 90
